# Plan a trajectory using a DMP.
# Configuration parameters to generate the trajectory.
start:
    positions: [0,0,0,0,0,0,0]
    velocities: [0,0,0,0,0,0,0]
    time: 0.0
goal:
   positions: [1.57,1.57,-1.57,-1.57,0,0,0]
